apiVersion: v1
kind: Service
metadata:
  name: svc-api-nginx
spec:
  selector:
    app: api-nginx
  ports:
  - port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nginx
spec:
  selector:
    matchLabels:
      app: api-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: api-nginx
    spec:
      containers:
      - name: api-server
        image: moyarka/db-api-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: moykey