apiVersion: v1
kind: Service
metadata:
  name: interface-service
spec:
  selector:
    app: interface
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
spec:
  selector:
    matchLabels:
      app: interface
  replicas: 4
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - name: interface
        image: interface:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000